name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to build branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f build  # Adjust 'build' to your output directory if different
          git commit -m "Deploy build" || echo "No changes to commit"
          git push -f origin HEAD:build
